**StreamShare Mobile App Privacy Policy**

*Effective Date: 28/08/2023*

We take your information privacy seriously. This privacy policy outlines how we collect, use, and protect the information you provide when using our application.

**No Data Collection**

We want to emphasize that the "StreamShare" app does not collect any personal data or any other confidential information. No information, such as your name, email address, location, browsing history, or any personal data, is collected, stored, or transmitted by our application.

**Use of Permissions**

The "StreamShare" app does not request or use any specific permissions from your Android device except for the following:

- `INTERNET`: This permission is used to enable network communication, allowing you to use the app's features that require internet access.
- `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE`: These permissions are used to read and write to external storage, allowing you to share and access files through the app.
- `ACCESS_NETWORK_STATE`: This permission is used to determine whether a network connection is available before attempting to access online resources.

**Communication**

Our application does not communicate any data to third parties, whether for commercial, advertising, or any other purposes. No information generated by your use of the application is shared with external parties.

**Data Storage and Usage**

While our application does not transmit any data, certain data, such as link history, is stored on your device for the sole purpose of enabling the application's functionality. This data is necessary for the proper operation of the app and is used solely within your device.

**Updates**

Throughout its lifecycle, our application may receive updates to enhance performance, fix bugs, or add new features. These updates do not alter our privacy policy in any way. Our commitment to protecting your data remains unchanged.

**Security**

While our application does not collect data, we take necessary measures to secure any technical information related to the application. We use standard security protocols and practices to ensure the integrity of the application and ensure proper functioning.

**Changes to Privacy Policy**

Please note that these privacy policies may be subject to change in the future. Any updates will be reflected in the latest version of the privacy policy, and you will be notified accordingly.

**Contact**

If you have questions or concerns regarding our privacy policy or the application itself, feel free to contact us.
